"""empty message

Revision ID: bb87aba9f427
Revises: 8c6280cbe5a5
Create Date: 2024-03-08 11:21:10.190539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb87aba9f427'
down_revision = '8c6280cbe5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=600),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    op.create_table('log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('todo_id', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
